"""Generates a starter TOML config that lists every Registry table in the workspace."""

from __future__ import annotations

import importlib.metadata
import logging
import re
from collections import defaultdict
from collections.abc import Sequence
from dataclasses import dataclass

import tomli_w

from latch_registry_export.schema import default_table_name

logger = logging.getLogger(__name__)

# TOML allows no control character other than tab in a comment.
_COMMENT_UNSAFE_RE = re.compile(r"[\x00-\x08\x0a-\x1f\x7f]+")


@dataclass(frozen=True)
class DiscoveredTable:
    """
    A Registry table found in a workspace.

    Attributes:
        id: The Registry table id.
        project_name: The display name of the Registry project that holds the table.
        display_name: The table display name, if it has one.
        column_keys: The table's Registry column keys, in Registry order.
    """

    id: str
    project_name: str
    display_name: str | None
    column_keys: tuple[str, ...]


def discover_tables(*, workspace_id: str) -> list[DiscoveredTable]:
    """
    List every Registry table in a Latch workspace, with its column keys.

    Args:
        workspace_id: The Latch workspace (account) id.

    Returns:
        One `DiscoveredTable` per table, sorted by numeric table id.
    """
    from latch.account import Account

    tables: list[DiscoveredTable] = []
    for project in Account(id=workspace_id).list_registry_projects():
        project_name = project.get_display_name()
        for table in project.list_tables():
            logger.debug("Fetching columns of table %s in project %r", table.id, project_name)
            tables.append(
                DiscoveredTable(
                    id=table.id,
                    project_name=project_name,
                    display_name=table.get_display_name(),
                    column_keys=tuple(table.get_columns() or {}),
                )
            )
    return sorted(tables, key=lambda t: int(t.id))


def to_config_toml(tables: Sequence[DiscoveredTable], *, workspace_id: str) -> str:
    """
    Render a config that exports every column of every table, for a user to hand-edit.

    Each entry suggests a `name`, chosen with `default_table_name` as the export does,
    except that a display name with no ASCII letters or digits gives `table_<id>`
    instead of a bare `col_`. When names collide, the table with the lowest id keeps
    the name and the others get the table id as a suffix. Each entry lists every
    column key in `include_columns`. A table without columns has no `include_columns`,
    so the export includes every column added to it later.

    Args:
        tables: The tables to list, in output order.
        workspace_id: The workspace the tables come from, recorded in a header comment.

    Returns:
        The TOML text. `load_table_configs` accepts it without edits.

    Raises:
        ValueError: `tables` is empty.
    """
    if not tables:
        raise ValueError(f"no Registry tables found in workspace {workspace_id}")
    names = _suggest_table_names(tables)
    tool_version = importlib.metadata.version("latch_registry_export")
    blocks = [
        f"# Generated by `latch_registry_export generate-config` "
        f"(latch_registry_export {tool_version}) from workspace {workspace_id}.\n"
        "# Edit names and column lists as needed before you run `latch_registry_export export`.\n"
    ]
    for table in tables:
        label = f"{table.project_name} / {table.display_name or '(no display name)'}"
        comments = [f"# {_COMMENT_UNSAFE_RE.sub(' ', label)}\n"]
        entry: dict[str, object] = {"id": table.id, "name": names[table.id]}
        if table.column_keys:
            entry["include_columns"] = list(table.column_keys)
        else:
            comments.append("# No columns yet, so the export includes every column added later.\n")
        # Write the `[[tables]]` header by hand: `tomli_w` renders an entry with only
        # scalar values as an inline `tables = [...]` array instead.
        blocks.append("".join(comments) + "[[tables]]\n" + tomli_w.dumps(entry))
    return "\n".join(blocks)


def _suggest_table_names(tables: Sequence[DiscoveredTable]) -> dict[str, str]:
    """
    Suggest a unique DuckDB table name for each table, keyed by table id.

    Start from `_initial_table_name`. In each group of tables that share a name, the
    table with the lowest id keeps it and the others get `_<id>`. Repeat until all
    names are unique. The loop ends because ids are unique and each pass makes the
    renamed names longer.
    """
    names = {t.id: _initial_table_name(t) for t in tables}
    while True:
        ids_by_name: defaultdict[str, list[str]] = defaultdict(list)
        for table_id, name in names.items():
            ids_by_name[name].append(table_id)
        renamed = [
            table_id for ids in ids_by_name.values() for table_id in sorted(ids, key=int)[1:]
        ]
        if not renamed:
            return names
        for table_id in renamed:
            names[table_id] = f"{names[table_id]}_{table_id}"


def _initial_table_name(table: DiscoveredTable) -> str:
    """Return `default_table_name`, or `table_<id>` where that is a bare `col_`."""
    name = default_table_name(table.id, table.display_name)
    # `sanitize_identifier` gives a bare `col_` for a name with no ASCII letters or digits.
    return f"table_{table.id}" if name == "col_" else name
