"""Generates a starter TOML config that lists every Registry table in the workspace."""

from __future__ import annotations

import re
from collections import Counter
from collections.abc import Sequence
from dataclasses import dataclass

import tomli_w

from latch_registry_export.schema import sanitize_identifier

_LINE_BREAK_RE = re.compile(r"[\r\n]+")


@dataclass(frozen=True)
class DiscoveredTable:
    """
    A Registry table found in the current workspace.

    Attributes:
        id: The Registry table id.
        project_name: The display name of the Registry project that holds the table.
        display_name: The table display name, if it has one.
        column_keys: The table's Registry column keys, in Registry order.
    """

    id: str
    project_name: str
    display_name: str | None
    column_keys: tuple[str, ...]


def discover_tables() -> list[DiscoveredTable]:
    """
    List every Registry table in the current Latch workspace, with its column keys.

    Returns:
        One `DiscoveredTable` per table, sorted by numeric table id.
    """
    from latch.account import Account

    tables: list[DiscoveredTable] = []
    for project in Account.current().list_registry_projects():
        project_name = project.get_display_name()
        for table in project.list_tables():
            tables.append(
                DiscoveredTable(
                    id=table.id,
                    project_name=project_name,
                    display_name=table.get_display_name(),
                    column_keys=tuple(table.get_columns() or {}),
                )
            )
    return sorted(tables, key=lambda t: int(t.id))


def to_config_toml(tables: Sequence[DiscoveredTable], *, workspace_id: str) -> str:
    """
    Render a config that exports every column of every table, for a user to hand-edit.

    Each entry suggests a `name`, chosen the same way the export chooses a table name.
    Names that collide get the table id as a suffix. Each entry includes every column
    key in `include_columns`; a table without columns has no `include_columns`.

    Args:
        tables: The tables to list, in output order.
        workspace_id: The workspace the tables come from, recorded in a header comment.

    Returns:
        The TOML text. `load_table_configs` accepts it without edits.

    Raises:
        ValueError: `tables` is empty.
    """
    if not tables:
        raise ValueError(f"no Registry tables found in workspace {workspace_id}")
    names = _suggest_table_names(tables)
    blocks = [
        f"# Generated by `latch_registry_export generate-config` from workspace {workspace_id}.\n"
        "# Edit names and column lists as needed before you run `latch_registry_export export`.\n"
    ]
    for table in tables:
        entry: dict[str, object] = {"id": table.id, "name": names[table.id]}
        if table.column_keys:
            entry["include_columns"] = list(table.column_keys)
        label = f"{table.project_name} / {table.display_name or '(no display name)'}"
        # Write the `[[tables]]` header by hand: `tomli_w` renders an entry with only
        # scalar values as an inline `tables = [...]` array instead.
        blocks.append(f"# {_LINE_BREAK_RE.sub(' ', label)}\n[[tables]]\n" + tomli_w.dumps(entry))
    return "\n".join(blocks)


def _suggest_table_names(tables: Sequence[DiscoveredTable]) -> dict[str, str]:
    """
    Suggest a unique DuckDB table name for each table, keyed by table id.

    Start from the name the export would resolve. Add `_<id>` to every name that
    collides, and repeat until all names are unique.
    """
    names = {
        t.id: sanitize_identifier(t.display_name) if t.display_name else f"table_{t.id}"
        for t in tables
    }
    while True:
        counts = Counter(names.values())
        colliding = [table_id for table_id, name in names.items() if counts[name] > 1]
        if not colliding:
            return names
        for table_id in colliding:
            names[table_id] = f"{names[table_id]}_{table_id}"
